/// Interactive generator for Kubernetes deployment manifests.
/// Run via:  zig build manifest
///
/// Prompts for credential mode and required values, then writes rendered YAML
/// files to zig-out/manifests/.
const std = @import("std");
const Io = std.Io;

var stdin_buf: [256]u8 = undefined;
var stdout_buf: [4096]u8 = undefined;

// ── prompt helpers ────────────────────────────────────────────────────────────

fn prompt(w: *Io.Writer, r: *Io.Reader, comptime label: []const u8) ![]const u8 {
    try w.print("{s}: ", .{label});
    try w.flush();
    const line = try r.takeDelimiter('\n') orelse return error.EndOfStream;
    return std.mem.trimEnd(u8, line, "\r");
}

fn promptDefault(w: *Io.Writer, r: *Io.Reader, comptime label: []const u8, default: []const u8) ![]const u8 {
    try w.print("{s} [{s}]: ", .{ label, default });
    try w.flush();
    const line = try r.takeDelimiter('\n') orelse return default;
    const trimmed = std.mem.trimEnd(u8, line, "\r");
    return if (trimmed.len == 0) default else trimmed;
}

fn promptChoice(w: *Io.Writer, r: *Io.Reader, comptime label: []const u8, comptime choices: []const []const u8) !usize {
    while (true) {
        try w.print("{s} (", .{label});
        for (choices, 0..) |c, i| {
            if (i > 0) try w.writeAll("/");
            try w.writeAll(c);
        }
        try w.writeAll("): ");
        try w.flush();
        const line = try r.takeDelimiter('\n') orelse return error.EndOfStream;
        const trimmed: []const u8 = std.mem.trimEnd(u8, line, "\r");
        for (choices, 0..) |c, i| {
            if (std.ascii.eqlIgnoreCase(trimmed, c)) return i;
        }
        try w.writeAll("  Please enter one of: ");
        for (choices, 0..) |c, i| {
            if (i > 0) try w.writeAll(", ");
            try w.writeAll(c);
        }
        try w.writeAll("\n");
    }
}

// ── template rendering ────────────────────────────────────────────────────────

fn render(allocator: std.mem.Allocator, template: []const u8, pairs: []const [2][]const u8) ![]u8 {
    var out: std.ArrayListUnmanaged(u8) = .empty;
    var src = template;
    while (src.len > 0) {
        var earliest_pos: usize = src.len;
        var earliest_pair: usize = pairs.len;
        for (pairs, 0..) |pair, i| {
            if (std.mem.indexOf(u8, src, pair[0])) |pos| {
                if (pos < earliest_pos) {
                    earliest_pos = pos;
                    earliest_pair = i;
                }
            }
        }
        if (earliest_pair == pairs.len) {
            try out.appendSlice(allocator, src);
            break;
        }
        try out.appendSlice(allocator, src[0..earliest_pos]);
        try out.appendSlice(allocator, pairs[earliest_pair][1]);
        src = src[earliest_pos + pairs[earliest_pair][0].len ..];
    }
    return out.toOwnedSlice(allocator);
}

fn base64Encode(allocator: std.mem.Allocator, s: []const u8) ![]u8 {
    const enc = std.base64.standard.Encoder;
    const len = enc.calcSize(s.len);
    const buf = try allocator.alloc(u8, len);
    _ = enc.encode(buf, s);
    return buf;
}

// ── templates ─────────────────────────────────────────────────────────────────

const tmpl_webhook_accesskey =
    \\# Static AccessKey deployment — generated by `zig build manifest`.
    \\---
    \\apiVersion: v1
    \\kind: Namespace
    \\metadata:
    \\  name: acme-dns-aliyun
    \\---
    \\apiVersion: v1
    \\kind: ServiceAccount
    \\metadata:
    \\  name: acme-dns-aliyun
    \\  namespace: acme-dns-aliyun
    \\---
    \\apiVersion: v1
    \\kind: Secret
    \\metadata:
    \\  name: alidns-credentials
    \\  namespace: acme-dns-aliyun
    \\type: Opaque
    \\data:
    \\  access-key-id: {{BASE64_ACCESS_KEY_ID}}
    \\  access-key-secret: {{BASE64_ACCESS_KEY_SECRET}}
    \\---
    \\apiVersion: apps/v1
    \\kind: Deployment
    \\metadata:
    \\  name: acme-dns-aliyun
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  replicas: 1
    \\  selector:
    \\    matchLabels:
    \\      app: acme-dns-aliyun
    \\  template:
    \\    metadata:
    \\      labels:
    \\        app: acme-dns-aliyun
    \\    spec:
    \\      serviceAccountName: acme-dns-aliyun
    \\      containers:
    \\        - name: webhook
    \\          image: {{IMAGE}}
    \\          imagePullPolicy: Always
    \\          env:
    \\            - name: WEBHOOK_GROUP_NAME
    \\              value: {{WEBHOOK_GROUP_NAME}}
    \\            - name: WEBHOOK_SOLVER_NAME
    \\              value: {{WEBHOOK_SOLVER_NAME}}
    \\            - name: WEBHOOK_PORT
    \\              value: "8080"
    \\            - name: WEBHOOK_TLS_CERT_FILE
    \\              value: /tls/tls.crt
    \\            - name: WEBHOOK_TLS_KEY_FILE
    \\              value: /tls/tls.key
    \\            - name: ALIBABA_CLOUD_REGION
    \\              value: {{ALIBABA_CLOUD_REGION}}
    \\            - name: ALIBABA_CLOUD_ACCESS_KEY_ID
    \\              valueFrom:
    \\                secretKeyRef:
    \\                  name: alidns-credentials
    \\                  key: access-key-id
    \\            - name: ALIBABA_CLOUD_ACCESS_KEY_SECRET
    \\              valueFrom:
    \\                secretKeyRef:
    \\                  name: alidns-credentials
    \\                  key: access-key-secret
    \\          ports:
    \\            - name: https
    \\              containerPort: 8080
    \\              protocol: TCP
    \\          resources:
    \\            limits:
    \\              cpu: 100m
    \\              memory: 128Mi
    \\            requests:
    \\              cpu: 50m
    \\              memory: 64Mi
    \\          livenessProbe:
    \\            httpGet:
    \\              path: /healthz
    \\              port: https
    \\              scheme: HTTPS
    \\            initialDelaySeconds: 5
    \\            periodSeconds: 10
    \\          readinessProbe:
    \\            httpGet:
    \\              path: /healthz
    \\              port: https
    \\              scheme: HTTPS
    \\            initialDelaySeconds: 5
    \\            periodSeconds: 10
    \\          volumeMounts:
    \\            - name: tls
    \\              mountPath: /tls
    \\              readOnly: true
    \\      volumes:
    \\        - name: tls
    \\          secret:
    \\            secretName: acme-dns-aliyun-tls
    \\---
    \\apiVersion: v1
    \\kind: Service
    \\metadata:
    \\  name: acme-dns-aliyun
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  selector:
    \\    app: acme-dns-aliyun
    \\  ports:
    \\    - name: https
    \\      port: 443
    \\      targetPort: https
    \\      protocol: TCP
    \\---
    \\apiVersion: cert-manager.io/v1
    \\kind: Issuer
    \\metadata:
    \\  name: acme-dns-aliyun-selfsign
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  selfSigned: {}
    \\---
    \\apiVersion: cert-manager.io/v1
    \\kind: Certificate
    \\metadata:
    \\  name: acme-dns-aliyun-tls
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  secretName: acme-dns-aliyun-tls
    \\  dnsNames:
    \\    - acme-dns-aliyun
    \\    - acme-dns-aliyun.acme-dns-aliyun
    \\    - acme-dns-aliyun.acme-dns-aliyun.svc
    \\    - acme-dns-aliyun.acme-dns-aliyun.svc.cluster.local
    \\  issuerRef:
    \\    name: acme-dns-aliyun-selfsign
    \\    kind: Issuer
    \\
;

const tmpl_webhook_rrsa =
    \\# RRSA (RAM Roles for Service Accounts) deployment — generated by `zig build manifest`.
    \\---
    \\apiVersion: v1
    \\kind: Namespace
    \\metadata:
    \\  name: acme-dns-aliyun
    \\---
    \\apiVersion: v1
    \\kind: ServiceAccount
    \\metadata:
    \\  name: acme-dns-aliyun
    \\  namespace: acme-dns-aliyun
    \\  annotations:
    \\    pod-identity.alibabacloud.com/role-name: {{ALIBABA_CLOUD_ROLE_ARN}}
    \\---
    \\apiVersion: apps/v1
    \\kind: Deployment
    \\metadata:
    \\  name: acme-dns-aliyun
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  replicas: 1
    \\  selector:
    \\    matchLabels:
    \\      app: acme-dns-aliyun
    \\  template:
    \\    metadata:
    \\      labels:
    \\        app: acme-dns-aliyun
    \\    spec:
    \\      serviceAccountName: acme-dns-aliyun
    \\      containers:
    \\        - name: webhook
    \\          image: {{IMAGE}}
    \\          imagePullPolicy: Always
    \\          env:
    \\            - name: WEBHOOK_GROUP_NAME
    \\              value: {{WEBHOOK_GROUP_NAME}}
    \\            - name: WEBHOOK_SOLVER_NAME
    \\              value: {{WEBHOOK_SOLVER_NAME}}
    \\            - name: WEBHOOK_PORT
    \\              value: "8080"
    \\            - name: WEBHOOK_TLS_CERT_FILE
    \\              value: /tls/tls.crt
    \\            - name: WEBHOOK_TLS_KEY_FILE
    \\              value: /tls/tls.key
    \\            - name: ALIBABA_CLOUD_REGION
    \\              value: {{ALIBABA_CLOUD_REGION}}
    \\            - name: ALIBABA_CLOUD_ROLE_ARN
    \\              value: {{ALIBABA_CLOUD_ROLE_ARN}}
    \\            - name: ALIBABA_CLOUD_OIDC_PROVIDER_ARN
    \\              value: {{ALIBABA_CLOUD_OIDC_PROVIDER_ARN}}
    \\            - name: ALIBABA_CLOUD_OIDC_TOKEN_FILE
    \\              value: /var/run/secrets/token
    \\          ports:
    \\            - name: https
    \\              containerPort: 8080
    \\              protocol: TCP
    \\          resources:
    \\            limits:
    \\              cpu: 100m
    \\              memory: 128Mi
    \\            requests:
    \\              cpu: 50m
    \\              memory: 64Mi
    \\          livenessProbe:
    \\            httpGet:
    \\              path: /healthz
    \\              port: https
    \\              scheme: HTTPS
    \\            initialDelaySeconds: 5
    \\            periodSeconds: 10
    \\          readinessProbe:
    \\            httpGet:
    \\              path: /healthz
    \\              port: https
    \\              scheme: HTTPS
    \\            initialDelaySeconds: 5
    \\            periodSeconds: 10
    \\          volumeMounts:
    \\            - name: tls
    \\              mountPath: /tls
    \\              readOnly: true
    \\            - name: oidc-token
    \\              mountPath: /var/run/secrets
    \\              readOnly: true
    \\      volumes:
    \\        - name: tls
    \\          secret:
    \\            secretName: acme-dns-aliyun-tls
    \\        - name: oidc-token
    \\          projected:
    \\            sources:
    \\              - serviceAccountToken:
    \\                  path: token
    \\                  expirationSeconds: 7200
    \\                  audience: "sts.aliyuncs.com"
    \\---
    \\apiVersion: v1
    \\kind: Service
    \\metadata:
    \\  name: acme-dns-aliyun
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  selector:
    \\    app: acme-dns-aliyun
    \\  ports:
    \\    - name: https
    \\      port: 443
    \\      targetPort: https
    \\      protocol: TCP
    \\---
    \\apiVersion: cert-manager.io/v1
    \\kind: Issuer
    \\metadata:
    \\  name: acme-dns-aliyun-selfsign
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  selfSigned: {}
    \\---
    \\apiVersion: cert-manager.io/v1
    \\kind: Certificate
    \\metadata:
    \\  name: acme-dns-aliyun-tls
    \\  namespace: acme-dns-aliyun
    \\spec:
    \\  secretName: acme-dns-aliyun-tls
    \\  dnsNames:
    \\    - acme-dns-aliyun
    \\    - acme-dns-aliyun.acme-dns-aliyun
    \\    - acme-dns-aliyun.acme-dns-aliyun.svc
    \\    - acme-dns-aliyun.acme-dns-aliyun.svc.cluster.local
    \\  issuerRef:
    \\    name: acme-dns-aliyun-selfsign
    \\    kind: Issuer
    \\
;

const tmpl_apiservice =
    \\# APIService — generated by `zig build manifest`.
    \\---
    \\apiVersion: apiregistration.k8s.io/v1
    \\kind: APIService
    \\metadata:
    \\  name: v1alpha1.{{WEBHOOK_GROUP_NAME}}
    \\  annotations:
    \\    cert-manager.io/inject-ca-from: acme-dns-aliyun/acme-dns-aliyun-tls
    \\spec:
    \\  group: {{WEBHOOK_GROUP_NAME}}
    \\  groupPriorityMinimum: 100
    \\  versionPriority: 100
    \\  version: v1alpha1
    \\  service:
    \\    name: acme-dns-aliyun
    \\    namespace: acme-dns-aliyun
    \\    port: 443
    \\---
    \\apiVersion: rbac.authorization.k8s.io/v1
    \\kind: ClusterRole
    \\metadata:
    \\  name: acme-dns-aliyun
    \\rules:
    \\  - apiGroups:
    \\      - {{WEBHOOK_GROUP_NAME}}
    \\    resources:
    \\      - "*"
    \\    verbs:
    \\      - create
    \\---
    \\apiVersion: rbac.authorization.k8s.io/v1
    \\kind: ClusterRoleBinding
    \\metadata:
    \\  name: acme-dns-aliyun
    \\roleRef:
    \\  apiGroup: rbac.authorization.k8s.io
    \\  kind: ClusterRole
    \\  name: acme-dns-aliyun
    \\subjects:
    \\  - apiGroup: ""
    \\    kind: ServiceAccount
    \\    name: cert-manager
    \\    namespace: cert-manager
    \\
;

const tmpl_clusterissuer =
    \\# ClusterIssuer example — generated by `zig build manifest`.
    \\---
    \\apiVersion: cert-manager.io/v1
    \\kind: ClusterIssuer
    \\metadata:
    \\  name: letsencrypt-{{WEBHOOK_SOLVER_NAME}}
    \\spec:
    \\  acme:
    \\    server: https://acme-v02.api.letsencrypt.org/directory
    \\    email: {{EMAIL_ADDRESS}}
    \\    privateKeySecretRef:
    \\      name: letsencrypt-alidns-account-key
    \\    solvers:
    \\      - dns01:
    \\          webhook:
    \\            groupName: {{WEBHOOK_GROUP_NAME}}
    \\            solverName: {{WEBHOOK_SOLVER_NAME}}
    \\
;

// ── main ──────────────────────────────────────────────────────────────────────

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;

    var stdout_file_writer = Io.File.stdout().writer(io, &stdout_buf);
    var stdin_file_reader = Io.File.stdin().readerStreaming(io, &stdin_buf);
    const w = &stdout_file_writer.interface;
    const r = &stdin_file_reader.interface;

    try w.writeAll(
        \\acme-dns-aliyun manifest generator
        \\===================================
        \\
    );
    try w.flush();

    // ── shared fields ─────────────────────────────────────────────────────────

    const group_name = try gpa.dupe(u8, try prompt(w, r, "Webhook group name (e.g. acme.mycompany.com)"));
    defer gpa.free(group_name);

    const solver_name = try gpa.dupe(u8, try promptDefault(w, r, "Webhook solver name", "alidns"));
    defer gpa.free(solver_name);

    const image = try gpa.dupe(u8, try promptDefault(w, r, "Container image", "ghcr.io/dzvon/acme-dns-aliyun:main"));
    defer gpa.free(image);

    const email = try gpa.dupe(u8, try prompt(w, r, "Let's Encrypt account email"));
    defer gpa.free(email);

    // ── credential mode ───────────────────────────────────────────────────────

    const mode_idx = try promptChoice(w, r, "Credential mode", &.{ "accesskey", "rrsa" });

    const WebhookContent = union(enum) { accesskey: []u8, rrsa: []u8 };
    var webhook_content: WebhookContent = undefined;

    if (mode_idx == 0) {
        const ak_id = try prompt(w, r, "Access Key ID");
        const ak_secret = try prompt(w, r, "Access Key Secret");
        const region = try gpa.dupe(u8, try promptDefault(w, r, "Region", "cn-hangzhou"));
        defer gpa.free(region);

        const b64_id = try base64Encode(gpa, ak_id);
        defer gpa.free(b64_id);
        const b64_secret = try base64Encode(gpa, ak_secret);
        defer gpa.free(b64_secret);

        webhook_content = .{ .accesskey = try render(gpa, tmpl_webhook_accesskey, &.{
            .{ "{{BASE64_ACCESS_KEY_ID}}", b64_id },
            .{ "{{BASE64_ACCESS_KEY_SECRET}}", b64_secret },
            .{ "{{WEBHOOK_GROUP_NAME}}", group_name },
            .{ "{{WEBHOOK_SOLVER_NAME}}", solver_name },
            .{ "{{IMAGE}}", image },
            .{ "{{ALIBABA_CLOUD_REGION}}", region },
        }) };
    } else {
        const role_arn = try gpa.dupe(u8, try prompt(w, r, "RAM Role ARN (e.g. acs:ram::1234567890:role/cert-manager-dns-solver)"));
        defer gpa.free(role_arn);
        const oidc_arn = try gpa.dupe(u8, try prompt(w, r, "OIDC Provider ARN (e.g. acs:ram::1234567890:oidc-provider/ack-rrsa-abcdef)"));
        defer gpa.free(oidc_arn);
        const region = try gpa.dupe(u8, try promptDefault(w, r, "Region", "cn-hangzhou"));
        defer gpa.free(region);

        webhook_content = .{ .rrsa = try render(gpa, tmpl_webhook_rrsa, &.{
            .{ "{{WEBHOOK_GROUP_NAME}}", group_name },
            .{ "{{WEBHOOK_SOLVER_NAME}}", solver_name },
            .{ "{{IMAGE}}", image },
            .{ "{{ALIBABA_CLOUD_REGION}}", region },
            .{ "{{ALIBABA_CLOUD_ROLE_ARN}}", role_arn },
            .{ "{{ALIBABA_CLOUD_OIDC_PROVIDER_ARN}}", oidc_arn },
        }) };
    }
    defer switch (webhook_content) {
        inline else => |s| gpa.free(s),
    };

    // ── render shared templates ───────────────────────────────────────────────

    const api_content = try render(gpa, tmpl_apiservice, &.{
        .{ "{{WEBHOOK_GROUP_NAME}}", group_name },
    });
    defer gpa.free(api_content);

    const issuer_content = try render(gpa, tmpl_clusterissuer, &.{
        .{ "{{WEBHOOK_GROUP_NAME}}", group_name },
        .{ "{{WEBHOOK_SOLVER_NAME}}", solver_name },
        .{ "{{EMAIL_ADDRESS}}", email },
    });
    defer gpa.free(issuer_content);

    // ── write output files ────────────────────────────────────────────────────

    // The build system passes the output dir as argv[1].
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    const out_dir_path: []const u8 = if (args.len > 1) args[1] else "zig-out/manifests";

    const cwd = Io.Dir.cwd();
    cwd.createDirPath(io, out_dir_path) catch |err| switch (err) {
        error.PathAlreadyExists => {},
        else => return err,
    };
    var out_dir = try cwd.openDir(io, out_dir_path, .{});
    defer out_dir.close(io);

    const webhook_filename = switch (webhook_content) {
        .accesskey => "webhook-accesskey.yaml",
        .rrsa => "webhook-rrsa.yaml",
    };
    const webhook_yaml = switch (webhook_content) {
        inline else => |s| s,
    };
    try out_dir.writeFile(io, .{ .sub_path = webhook_filename, .data = webhook_yaml });
    try out_dir.writeFile(io, .{ .sub_path = "apiservice.yaml", .data = api_content });
    try out_dir.writeFile(io, .{ .sub_path = "clusterissuer.yaml", .data = issuer_content });

    try w.print(
        \\
        \\Manifests written to {s}/
        \\  {s}
        \\  apiservice.yaml
        \\  clusterissuer.yaml
        \\
        \\Apply with:
        \\  kubectl apply -f {s}/{s}
        \\  kubectl apply -f {s}/apiservice.yaml
        \\  kubectl apply -f {s}/clusterissuer.yaml
        \\
    , .{
        out_dir_path, webhook_filename,
        out_dir_path, webhook_filename,
        out_dir_path, out_dir_path,
    });
    try w.flush();
}
